In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.backends.cudnn as cudnn
from torch.autograd import Variable
import torch.optim as optim

import torchvision
import torchvision.transforms as transforms

from recnet import *

In [2]:
normalize = transforms.Normalize(mean=[0.507, 0.487, 0.441], std=[0.267, 0.256, 0.276])

train_dataset = torchvision.datasets.CIFAR100(
    root='../data',
    train=True,
    download=True,
    transform=transforms.Compose([
        transforms.RandomCrop(32, padding=4),
        transforms.RandomHorizontalFlip(),
        transforms.ToTensor(),
        normalize,
    ]))

Files already downloaded and verified


In [3]:
trainloader = torch.utils.data.DataLoader(train_dataset, batch_size=128, shuffle=True, )

In [4]:
affine = recnet_affine_gru(num_classes=100)

In [32]:
id(model.layer3[1].convs[1])

139802828424360

In [25]:
id(sharedBNmodel.layer3[1].batchNorms[1])

139663541974240

In [6]:
recnet=RecNet(RecNetBlock, [9,9,9], num_classes=100)

In [8]:
resnet=resnet56_cifar()

In [5]:
input = train_dataset[0][0]

In [6]:
affine(input.unsqueeze(0))

tensor([[-0.1176, -0.1063,  0.4060, -0.1542,  0.2732,  0.0602, -0.2077,
          0.0125,  0.1504, -0.0155, -0.1646,  0.1680,  0.2069, -0.0662,
          0.4175, -0.1538, -0.0847, -0.4172, -0.1049, -0.1144, -0.0767,
         -0.1614, -0.0965, -0.1428, -0.2130, -0.0007, -0.1285,  0.4443,
         -0.5583,  0.1659, -0.0241, -0.0242,  0.2199,  0.0699, -0.2350,
          0.4489, -0.1184, -0.1316, -0.5332,  0.2916,  0.0573,  0.5901,
         -0.1615, -0.2438,  0.2642,  0.3189, -0.0036,  0.0137, -0.0356,
         -0.4645,  0.3817, -0.0219, -0.1415, -0.0867, -0.4495, -0.0777,
         -0.0211, -0.2860,  0.3525,  0.2356,  0.1787,  0.3081, -0.3415,
         -0.1195,  0.4698, -0.2288,  0.1739, -0.5521, -0.3436, -0.0600,
          0.1867,  0.0316,  0.0569,  0.1323,  0.1464, -0.4656, -0.1843,
          0.0632,  0.0397, -0.0203,  0.2190, -0.0213, -0.0342, -0.0558,
          0.1485,  0.1399,  0.1515, -0.1060,  0.2824,  0.3287,  0.1398,
         -0.1058, -0.0052,  0.4014,  0.1272, -0.1089, -0.2523,  

In [7]:
model(input.unsqueeze(0))

tensor([[-0.5430,  0.9464, -2.0052, -0.2730,  5.2042,  1.0475,  0.5781,
          0.1904, -1.9135,  0.4301, -1.5898,  2.2755,  4.7336, -7.0189,
          1.0013, -0.8710, -0.2501,  0.1143,  0.9919,  2.3600, -1.1835,
          2.8684, -0.6146,  1.9053, -1.8000, -4.9578, -1.4480,  3.6601,
         -0.7743, -0.7184,  0.0803,  1.3834,  2.4053,  2.1539,  0.0549,
         -0.4088, -0.6650, -1.1864,  0.4159, -0.4570,  2.4299,  4.2281,
         -1.8265,  2.7145,  1.2926, -0.3088, -3.9581, -2.2106,  0.4956,
          4.4439,  1.0773, -1.4914,  1.9130,  2.2549, -3.6651, -1.0887,
          0.5032, -1.7611,  0.7184,  1.4740, -0.4332,  2.2522,  0.9401,
         -0.8512,  1.1640, -1.8171,  1.1307, -3.3180, -0.1261,  2.1789,
          1.3191, -0.6283,  1.7195, -1.7208,  1.0544,  0.5622,  0.8289,
          1.4680,  1.8146, -0.4683,  2.1391,  0.8841,  1.3736,  0.1287,
          1.6899,  4.2408,  0.1740,  2.4508,  2.6387,  1.8606, -4.9750,
          1.8760,  0.3096, -4.0941, -2.3259, -2.7146, -2.7906, -

In [8]:
id(model.layer1[4].convs[0])

140058653458504

In [10]:
id(model.layer1[5].convs[0])

140058653458504

In [98]:
        BatchNormList=[[nn.ModuleList([nn.BatchNorm2d(16) for _ in range(2)]) for _ in range(9)] for _ in range(3)]


In [24]:
id(model.layer2[2].batchNorms)

140139447197936

In [17]:
id(resnet.layer2[2].conv1)

140058649907944

In [ ]:
model

In [4]:
model_prelu= RecNet(RecNetBlock_postrelu, [9,9,9], num_classes=100)

In [ ]:
model_prelu

In [7]:
model_prelu(input.unsqueeze(0))

tensor([[ 1.3692, -0.3770,  0.8205,  2.3196, -1.2589,  0.0089,  0.6870,
          1.4174,  3.7652, -0.9951, -2.9569, -3.3858,  2.8897,  3.4226,
          0.6408, -1.3675, -7.6292,  2.7452, -0.6200,  3.8776, -1.8443,
          1.2568,  1.2669, -0.7591,  3.9481, -0.6248,  1.3990,  1.2554,
          7.4346,  1.9507, -0.4943,  0.8131, -0.8727, -2.8915, -5.2966,
         -1.1505,  2.3969, -0.9881,  4.6168, -0.4027,  2.4973,  2.9641,
         -0.3643, -2.7919,  5.3732, -0.0409,  3.3976, -1.4348, -0.9936,
         -1.4449, -0.3176, -0.7703, -3.3360, -1.4561,  1.0225, -1.9184,
         -1.8180,  1.9675, -5.8880, -1.3760, -5.4642, -0.4286,  1.0017,
          0.6553,  1.4423, -3.8724,  1.9909,  0.3804,  0.0551, -1.9576,
          0.6028, -0.1065, -0.9554, -1.9363,  1.4746,  3.6003, -7.0367,
         -3.5777, -0.3812,  0.4932, -0.6902, -3.7634,  2.3211, -0.4370,
         -1.4916,  2.0099, -2.7587, -1.3783, -1.6386, -3.0498, -0.5225,
         -1.0344, -3.7878, -3.8541, -5.6407, -4.3768, -1.5816, -

In [10]:
id(sharedBNmodel.layer1[3].batchNorms)

140367299698136

In [5]:
for param in (affine.AffineIterator())L

Parameter containing:
tensor([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])
Parameter containing:
tensor([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.])
Parameter containing:
tensor([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0

In [12]:
'linearA' in ['linearA']

True

TypeError: object of type 'generator' has no len()