In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.backends.cudnn as cudnn
from torch.autograd import Variable


import torchvision
import torchvision.transforms as transforms

from recnet import *

In [2]:
normalize = transforms.Normalize(mean=[0.507, 0.487, 0.441], std=[0.267, 0.256, 0.276])

train_dataset = torchvision.datasets.CIFAR100(
    root='../data',
    train=True,
    download=True,
    transform=transforms.Compose([
        transforms.RandomCrop(32, padding=4),
        transforms.RandomHorizontalFlip(),
        transforms.ToTensor(),
        normalize,
    ]))

Files already downloaded and verified


In [3]:
model = RecNet(RecNetBlock, [9,9,9], num_classes=100)
sharedBNmodel= RecNet_SharedBNs(RecNetBlock_SharedBN, [9,9,9], num_classes=100)
lnModel = RecNet_LayerNorm(RecNetLayerNormBlock, [9,9,9], num_classes=100)
resnet = ResNet_Cifar(block=BasicBlock, layers=[9,9,9], num_classes=100)

In [32]:
id(model.layer3[1].convs[1])

139802828424360

In [25]:
id(sharedBNmodel.layer3[1].batchNorms[1])

139663541974240

True

In [4]:
input = train_dataset[0][0]

In [6]:
lnModel(input.unsqueeze(0))

tensor([[ 0.0738,  0.4639, -0.2838,  0.2319,  0.0207, -0.0879, -0.0247,
          0.0858, -0.2097,  0.1847, -0.2028, -0.3053,  0.0893, -0.1170,
          0.0073,  0.1942,  0.1868, -0.4365, -0.0911,  0.1373,  0.0899,
          0.2086, -0.7741,  0.2982,  0.1023,  0.2777,  0.3179, -0.3008,
         -0.0662,  0.1667, -0.0962, -0.2279,  0.1590,  0.3797, -0.0855,
          0.0078,  0.4720,  0.1709, -0.1114,  0.6980, -0.1003,  0.2347,
          0.0843, -0.0365,  0.0977,  0.1020, -0.2556,  0.0657, -0.1027,
          0.2876,  0.1786,  0.1612,  0.1404, -0.2517, -0.1205,  0.0605,
          0.3778, -0.4084,  0.3425, -0.0990,  0.3152, -0.0358,  0.3436,
          0.2507, -0.4033, -0.2139,  0.0331, -0.2896, -0.1110, -0.1628,
         -0.2844,  0.2157,  0.1659, -0.1983, -0.2521, -0.2863,  0.2960,
         -0.1477, -0.1595, -0.0323, -0.2761, -0.0044, -0.3963,  0.3224,
         -0.0116,  0.6679,  0.3194, -0.0071, -0.3322, -0.1689, -0.0551,
         -0.2722, -0.1112,  0.2438,  0.2712, -0.2707,  0.0965, -

In [7]:
model(input.unsqueeze(0))

tensor([[-0.5430,  0.9464, -2.0052, -0.2730,  5.2042,  1.0475,  0.5781,
          0.1904, -1.9135,  0.4301, -1.5898,  2.2755,  4.7336, -7.0189,
          1.0013, -0.8710, -0.2501,  0.1143,  0.9919,  2.3600, -1.1835,
          2.8684, -0.6146,  1.9053, -1.8000, -4.9578, -1.4480,  3.6601,
         -0.7743, -0.7184,  0.0803,  1.3834,  2.4053,  2.1539,  0.0549,
         -0.4088, -0.6650, -1.1864,  0.4159, -0.4570,  2.4299,  4.2281,
         -1.8265,  2.7145,  1.2926, -0.3088, -3.9581, -2.2106,  0.4956,
          4.4439,  1.0773, -1.4914,  1.9130,  2.2549, -3.6651, -1.0887,
          0.5032, -1.7611,  0.7184,  1.4740, -0.4332,  2.2522,  0.9401,
         -0.8512,  1.1640, -1.8171,  1.1307, -3.3180, -0.1261,  2.1789,
          1.3191, -0.6283,  1.7195, -1.7208,  1.0544,  0.5622,  0.8289,
          1.4680,  1.8146, -0.4683,  2.1391,  0.8841,  1.3736,  0.1287,
          1.6899,  4.2408,  0.1740,  2.4508,  2.6387,  1.8606, -4.9750,
          1.8760,  0.3096, -4.0941, -2.3259, -2.7146, -2.7906, -

In [8]:
id(model.layer1[4].convs[0])

140058653458504

In [10]:
id(model.layer1[5].convs[0])

140058653458504

In [98]:
        BatchNormList=[[nn.ModuleList([nn.BatchNorm2d(16) for _ in range(2)]) for _ in range(9)] for _ in range(3)]


In [24]:
id(model.layer2[2].batchNorms)

140139447197936

In [17]:
id(resnet.layer2[2].conv1)

140058649907944

In [8]:
model

RecNet(
  (conv1): Conv2d(3, 16, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
  (bn1): BatchNorm2d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace)
  (layer1): Sequential(
    (0): RecNetBlock(
      (convs): ModuleList(
        (0): Conv2d(16, 16, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (1): Conv2d(16, 16, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      )
      (batchNorms): ModuleList(
        (0): BatchNorm2d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (1): BatchNorm2d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
      (relu): ReLU(inplace)
    )
    (1): RecNetBlock(
      (convs): ModuleList(
        (0): Conv2d(16, 16, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (1): Conv2d(16, 16, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      )
      (batchNorms): ModuleLis

In [4]:
model_prelu= RecNet(RecNetBlock_postrelu, [9,9,9], num_classes=100)

In [5]:
model_prelu

RecNet(
  (conv1): Conv2d(3, 16, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
  (bn1): BatchNorm2d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace)
  (layer1): Sequential(
    (0): RecNetBlock_postrelu(
      (convs): ModuleList(
        (0): Conv2d(16, 16, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (1): Conv2d(16, 16, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      )
      (batchNorms): ModuleList(
        (0): BatchNorm2d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (1): BatchNorm2d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
      (relu): ReLU(inplace)
    )
    (1): RecNetBlock_postrelu(
      (convs): ModuleList(
        (0): Conv2d(16, 16, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (1): Conv2d(16, 16, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      )
      (batc

In [7]:
model_prelu(input.unsqueeze(0))

tensor([[ 1.3692, -0.3770,  0.8205,  2.3196, -1.2589,  0.0089,  0.6870,
          1.4174,  3.7652, -0.9951, -2.9569, -3.3858,  2.8897,  3.4226,
          0.6408, -1.3675, -7.6292,  2.7452, -0.6200,  3.8776, -1.8443,
          1.2568,  1.2669, -0.7591,  3.9481, -0.6248,  1.3990,  1.2554,
          7.4346,  1.9507, -0.4943,  0.8131, -0.8727, -2.8915, -5.2966,
         -1.1505,  2.3969, -0.9881,  4.6168, -0.4027,  2.4973,  2.9641,
         -0.3643, -2.7919,  5.3732, -0.0409,  3.3976, -1.4348, -0.9936,
         -1.4449, -0.3176, -0.7703, -3.3360, -1.4561,  1.0225, -1.9184,
         -1.8180,  1.9675, -5.8880, -1.3760, -5.4642, -0.4286,  1.0017,
          0.6553,  1.4423, -3.8724,  1.9909,  0.3804,  0.0551, -1.9576,
          0.6028, -0.1065, -0.9554, -1.9363,  1.4746,  3.6003, -7.0367,
         -3.5777, -0.3812,  0.4932, -0.6902, -3.7634,  2.3211, -0.4370,
         -1.4916,  2.0099, -2.7587, -1.3783, -1.6386, -3.0498, -0.5225,
         -1.0344, -3.7878, -3.8541, -5.6407, -4.3768, -1.5816, -

In [10]:
id(sharedBNmodel.layer1[3].batchNorms)

140367299698136