In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.backends.cudnn as cudnn
from torch.autograd import Variable
import torch.optim as optim

import torchvision
import torchvision.transforms as transforms

from recnet import *

In [2]:
normalize = transforms.Normalize(mean=[0.507, 0.487, 0.441], std=[0.267, 0.256, 0.276])

train_dataset = torchvision.datasets.CIFAR100(
    root='../data',
    train=True,
    download=True,
    transform=transforms.Compose([
        transforms.RandomCrop(32, padding=4),
        transforms.RandomHorizontalFlip(),
        transforms.ToTensor(),
        normalize,
    ]))

Files already downloaded and verified


In [ ]:
trainloader = torch.utils.data.DataLoader(train_dataset, batch_size=128, shuffle=True, )

In [3]:
affine = recnet_affine_modular(num_classes=100, gruLoss=True)

In [ ]:
affine

In [ ]:
recnet=RecNet(RecNetBlock, [9,9,9], num_classes=100)

In [ ]:
resnet=resnet56_cifar()

In [4]:
input = train_dataset[0][0]

In [5]:
input

tensor([[[ 0.8771,  0.9358,  1.3324,  ...,  1.8464, -1.8989, -1.8989],
         [ 0.5539,  0.9211,  1.2149,  ...,  1.8464, -1.8989, -1.8989],
         [ 0.4071,  0.6861,  0.4071,  ...,  1.8464, -1.8989, -1.8989],
         ...,
         [-1.3995, -1.6198, -0.7826,  ..., -0.6211, -1.8989, -1.8989],
         [-1.8989, -1.8989, -1.8989,  ..., -1.8989, -1.8989, -1.8989],
         [-1.8989, -1.8989, -1.8989,  ..., -1.8989, -1.8989, -1.8989]],

        [[ 1.1461,  1.2839,  1.6516,  ...,  2.0039, -1.9023, -1.9023],
         [ 0.8703,  1.2227,  1.4065,  ...,  2.0039, -1.9023, -1.9023],
         [ 0.6099,  0.6405,  0.1657,  ...,  2.0039, -1.9023, -1.9023],
         ...,
         [-1.3509, -1.7645, -0.7075,  ..., -0.0335, -1.9023, -1.9023],
         [-1.9023, -1.9023, -1.9023,  ..., -1.9023, -1.9023, -1.9023],
         [-1.9023, -1.9023, -1.9023,  ..., -1.9023, -1.9023, -1.9023]],

        [[ 0.8034,  1.0308,  1.5565,  ...,  2.0254, -1.5978, -1.5978],
         [ 0.3203,  0.8461,  1.1444,  ...,  2

In [5]:
 affine(input.unsqueeze(0))

std for each channel:  tensor([nan., nan., nan., nan., nan., nan., nan., nan., nan., nan.,
        nan., nan., nan., nan., nan., nan.])
tensor([[[nan., nan., nan., nan., nan., nan., nan., nan., nan., nan.,
          nan., nan., nan., nan., nan., nan., nan., nan., nan., nan.,
          nan., nan., nan., nan., nan., nan., nan., nan., nan., nan.,
          nan., nan.]]])
std for each channel:  tensor([nan., nan., nan., nan., nan., nan., nan., nan., nan., nan.,
        nan., nan., nan., nan., nan., nan.])
tensor([[[nan., nan., nan., nan., nan., nan., nan., nan., nan., nan.,
          nan., nan., nan., nan., nan., nan., nan., nan., nan., nan.,
          nan., nan., nan., nan., nan., nan., nan., nan., nan., nan.,
          nan., nan.]]])
std for each channel:  tensor([nan., nan., nan., nan., nan., nan., nan., nan., nan., nan.,
        nan., nan., nan., nan., nan., nan.])
tensor([[[nan., nan., nan., nan., nan., nan., nan., nan., nan., nan.,
          nan., nan., nan., nan., nan., nan., nan., 

(tensor([[-0.0537,  0.4503,  0.1218, -0.4876, -0.2359,  0.1525, -0.0189,
           0.2685,  0.3082,  0.0527, -0.0324, -0.2322, -0.6253,  0.0939,
          -0.5322,  0.2155, -0.2141,  0.3095,  0.0183, -0.3179,  0.0994,
           0.1029,  0.5267, -0.0050, -0.1032,  0.1647, -0.3082, -0.3309,
           0.6473,  0.4963, -0.0300, -0.0412,  0.2034, -0.0061,  0.4039,
          -0.1161, -0.2709,  0.5555, -0.0520, -0.0661, -0.1671,  0.0915,
           0.1023,  0.2410,  0.0214,  0.0402, -0.2021, -0.1365,  0.0750,
           0.2071, -0.3095,  0.1635,  0.0520,  0.2834, -0.0695,  0.6062,
           0.2590, -0.2803, -0.4592,  0.2812,  0.3168,  0.0641,  0.1582,
          -0.1639, -0.2256, -0.0410, -0.2058, -0.5957, -0.7126, -0.2477,
          -0.1156,  0.3712, -0.3654, -0.2093, -0.3244,  0.1264,  0.1298,
          -0.0473,  0.2728, -0.2788,  0.4639, -0.0719, -0.1754,  0.4112,
          -0.0056, -0.6041, -0.2771, -0.0199, -0.3923, -0.1551, -0.1794,
           0.6327, -0.1851, -0.4052,  0.1344,  0.29

In [ ]:
affine

In [ ]:
id(model.layer1[4].convs[0])

In [ ]:
id(model.layer1[5].convs[0])

In [ ]:
        BatchNormList=[[nn.ModuleList([nn.BatchNorm2d(16) for _ in range(2)]) for _ in range(9)] for _ in range(3)]


In [ ]:
id(model.layer2[2].batchNorms)

In [ ]:
id(resnet.layer2[2].conv1)

In [ ]:
model

In [ ]:
model_prelu= RecNet(RecNetBlock_postrelu, [9,9,9], num_classes=100)

In [ ]:
model_prelu

In [ ]:
model_prelu(input.unsqueeze(0))

In [ ]:
id(sharedBNmodel.layer1[3].batchNorms)

In [ ]:
for param in (affine.AffineIterator())L

In [ ]:
'linearA' in ['linearA']

In [ ]:
out = torch.randn(128,64,8,8)

In [ ]:
torch.sum(torch.sum(out, 3),2).mean(0)

In [ ]:
torch.mean(torch.mean(torch.mean(out, 3),2), 0)

In [ ]:
out = torch.randn(64,128,8,8)

In [ ]:
out[0].sum(2).sum(1).mean()

In [ ]:
criterion=nn.CrossEntropyLoss()

In [ ]:
out2[0][0].mean()

In [ ]:
out2 = out.reshape(64,128,8,8)

In [ ]:
outmeans1 = []

In [ ]:
input = torch.randn(1,16,32,32)

In [ ]:
residualConv = nn.Conv2d(16, 32, kernel_size=1, stride=1, bias=False)

In [ ]:
testres = residualConv(input)

In [ ]:
testres